language: csharp
solution: QueryBuilder.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore QueryBuilder.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release QueryBuilder.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MeuDindin.Domain.Test/bin/Release/QueryBuilder.Test.dll
